version: '3'
services:
  server:
    image: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - "panam-net"
    tty: true
    # stdin_open: true
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7-fpm
    restart: always
    volumes:
      - ./code:/code
      - ./php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php.ini-production:/usr/local/etc/php/php.ini-production
    networks:
      - "panam-net"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    networks:
      - "panam-net"

networks:
  panam-net:
    driver: bridge

#connect psql : 
#docker exec -it panam_postgres_1 psql -U postgres